#pragma once

#define IGNORE_MOD_TAP_INTERRUPT
#define UNICODE_SELECTED_MODES UC_LNX

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#ifdef TAPPING_TOGGLE
#undef TAPPING_TOGGLE
#endif
#define TAPPING_TOGGLE 2